In [ ]:
#1
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [ ]:
#2
import numpy as np

def l2_dist(a, b):
  result = ((a-b) * (a-b)).sum()
  result = result ** 0.5
  return result

In [ ]:
a = np.random.rand(20,20)
b = np.random.rand(20,20)

In [ ]:
l2_dist(np.reshape(a, (20*20)), np.reshape(b, (20*20, 1)))

162.50220685958044

In [ ]:
l2_dist(a, b)

7.996568862799049

In [ ]:
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

7.996568862799049

In [ ]:
l2_dist(a.T, b.T)

7.996568862799049

In [ ]:
#3
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1,2,3,4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1, 4, 4)

print (a1, a2, a3, a4, a5)

[0.91043528 0.26497746 0.60313199 0.21201468] [[0.32729331]
 [0.37014372]
 [0.70732247]
 [0.58196835]] [[1 2 3 4]] [1 2 3] [1. 2. 3. 4.]


In [ ]:
a3.shape == a4.shape

False

In [ ]:
a4.ndim == 1 #Porem no enunciado está 'a4.ndim()', tornando esta alternativa incorreta

True

In [ ]:
a5.shape == a1.shape

True

In [ ]:
a1.shape == a2.shape

False

In [ ]:
#4
old = np.array([[1,1,1], [1,1,1]])
new = old
new[0, :2] = 0
print(old)
               

[[0 0 1]
 [1 1 1]]


In [ ]:
#5
array = np.random.rand(6,6)
array[2:4,2:4]

array([[0.09647018, 0.81375378],
       [0.26810537, 0.66201681]])

In [ ]:
print(array)

[[0.45627586 0.69774034 0.88080643 0.27088367 0.92143886 0.411127  ]
 [0.09572988 0.99903539 0.92182843 0.64074157 0.04033709 0.79355978]
 [0.65272878 0.68846341 0.09647018 0.81375378 0.86429465 0.06364456]
 [0.36518791 0.67286053 0.26810537 0.66201681 0.754923   0.94131114]
 [0.15039267 0.95584863 0.55301818 0.34564644 0.89892762 0.37818315]
 [0.46937019 0.63261329 0.06680182 0.60171986 0.77601646 0.26796477]]


In [ ]:
#6
s = 'ACBCAC'
re.findall('^AC', s)

['AC']

In [ ]:
#7
s = "ACAACAACAAAB"
result = re.findall('A{1,2}', s)
L = len(result)
print(L, result)

5 ['A', 'AA', 'AA', 'AA', 'A']


In [ ]:
#8
#PASTE TEXT

[(]\d{3}[)]\d{3}[-]\d{4}

SyntaxError: ignored